language: go

go:
  - "1.11.x"

services:
  - mysql

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/golang/dep/cmd/dep

install: true

before_script:
  - mysql -uroot -e "create database test"

script: 
  - dep ensure
  - make create-dotenv
  - cat .env
  - make && make test