language: go

go:
  - "1.11.x"

services:
  - mysql

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/golang/dep/cmd/dep

install: true

before_script:
  - make clean-all
  - make dep-install
  - make deps
  - mysql -uroot -e "create database test"

script: 
  - dep ensure
  - make
  - make test